# netlify.toml

[[plugins]]
package = "/plugins/netlify-plugin-instagramFeed"
    [plugins.inputs]
    instagramKey = "IGQVJXVzBTOVNuTy1CaHdYeXEyT01URGlXd0tZAWU1ZAYlZA3TDFKM0x5dnZAJaW9DdFdBMmx3XzZAMMGNWZA24wTzdTZA1E5bXhySDJmUW1BYXdZAcGh2MVN2MFpKeGZAVQWw0VTgtQ0drOW53"

# Config for the Netlify Build Plugin: netlify-plugin-fetch-feeds
[[plugins]]
  package = "netlify-plugin-fetch-feeds"
 
  [plugins.inputs]
    # Where should data files reside
    dataDir = "site/_data"
 
    # All the feeds we wish to gather for use in the build
 
    [[plugins.inputs.feeds]]
      name = "Instagram"
      url = "https://graph.instagram.com/me/media?fields=timestamp,media_type,media_url,thumbnail_url,permalink&access_token=IGQVJXVzBTOVNuTy1CaHdYeXEyT01URGlXd0tZAWU1ZAYlZA3TDFKM0x5dnZAJaW9DdFdBMmx3XzZAMMGNWZA24wTzdTZA1E5bXhySDJmUW1BYXdZAcGh2MVN2MFpKeGZAVQWw0VTgtQ0drOW53"
      ttl = 3600